<a href="https://colab.research.google.com/github/gavindoughtie/pytorch_class/blob/main/udemy_pytorch_01_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction to Tensors

### Creating tensors

Pytorch tensors are created using `torch.Tensor()` https://pytorch.org/docs/stable/ensors.html

In [ ]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 5, 4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]   

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

In [ ]:
TENSOR[0].shape

torch.Size([3, 3])

In [ ]:
MYTENSOR = torch.tensor([5, 5, 5])
TENSOR * MYTENSOR

tensor([[[ 5, 10, 15],
         [15, 30, 45],
         [10, 25, 20]]])

### Radom Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
# Create a random tensor of shape 3,4

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8779, 0.4148, 0.5564, 0.0864],
        [0.7385, 0.1350, 0.3877, 0.9289],
        [0.6338, 0.0156, 0.7334, 0.3404]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(225, 224, 3)) # height, width, color channels, but often channels can come first
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([225, 224, 3]), 3)

# Zeros and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4), dtype=torch.int8)
ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int8)

In [ ]:
ones.dtype

torch.int8

# Creating a range of tensors and tensors-like

In [ ]:
# Use torch.range()
torch.range(0, 10)

<ipython-input-25-74fde6f68c60>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
evens = torch.arange(0, 10, step=2)

In [ ]:
# Creating tensors like
evens_zeros = torch.zeros_like(evens)
evens_zeros

tensor([0, 0, 0, 0, 0])

# Tensor datatypes

**Note: ** Tensor datatypes can be one of the 3 big areas for finding errors in PyTorch and deep learning:

1. Tensors not right datatype
1. Tensors not right shape
1. Tensors not on the right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3, 6, 9], dtype=torch.float32, # type of the tensor (float16, float32)
                               device="cpu", # actual hardware. Can also be 'cuda' or maybe 'tpu',
                               # tensors cannot operate across different device types
                               requires_grad=False # whether this tensor tracks gradients
                               )
(float_32_tensor, float_32_tensor.dtype)

(tensor([3., 6., 9.]), torch.float32)

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
multiplied = float_16_tensor * float_32_tensor
(multiplied, multiplied.dtype)

(tensor([ 9., 36., 81.]), torch.float32)

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. To get datatype from a tensor `tensor.dtype`
2. To get the shape: `tensor.shape`
3. To get the device: `tensor.device`

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 5)

In [ ]:
print(some_tensor)
print(f"Datatype: {some_tensor.dtype}")
print(f"Shape: {some_tensor.shape} (identical to Size: {some_tensor.size()})")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.1078, 0.2624, 0.5788, 0.2485, 0.8993],
        [0.3869, 0.8659, 0.1179, 0.6206, 0.1696],
        [0.3795, 0.0941, 0.1789, 0.7240, 0.1532]])
Datatype: torch.float32
Shape: torch.Size([3, 5]) (identical to Size: torch.Size([3, 5]))
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning

* element-wise multiplication
* matrix multiplication (dot product)

More information on multiplying matrices: https://www.mathsisfun.com/algebra/matrix-multiplying.html

Also, play around with: http://matrixmultiplication.xyz/

There are two main rrules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) * (2, 3)` -> `(3, 3)`



In [ ]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.3156, 0.1036, 0.1378],
        [0.2821, 0.1446, 0.1754],
        [0.6989, 0.4074, 0.4839]])

In [ ]:
# Element wise multiplication

print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication

print(f'1D dot product {torch.matmul(tensor, tensor)}')

print(f'Matrix multiplication by hand: {tensor[0] * tensor[0] + tensor[1] * tensor[1] + tensor[2] * tensor[2]}')

m1 = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
    ])

m2 = torch.tensor([
    [7, 8],
    [9, 10],
    [11, 12]
])

(m1.shape,
m2.shape)

1D dot product 14
Matrix multiplication by hand: 14


(torch.Size([2, 3]), torch.Size([3, 2]))

In [ ]:
m2 @ m1

tensor([[ 39,  54,  69],
        [ 49,  68,  87],
        [ 59,  82, 105]])

In [ ]:
torch.matmul(m2, m1)

tensor([[ 39,  54,  69],
        [ 49,  68,  87],
        [ 59,  82, 105]])

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 482 µs, sys: 0 ns, total: 482 µs
Wall time: 1.36 ms


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 76 µs, sys: 13 µs, total: 89 µs
Wall time: 92.7 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [ ]:
# Shapes for matrix multiplication:

tensor_A = torch.tensor([
    [1, 2], 
    [3, 4], 
    [5, 6]
    ])
tensor_B = torch.tensor([
    [7, 10],
    [8, 11],
    [9, 12]
    ])

In [ ]:
torch.mm(tensor_A, tensor_B.T) # mm is the same as matmul, "T" is the transpose attribute

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor

In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
# The matrix operation works when a tensor is transposed
print(f'Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}')

result = torch.mm(tensor_A, tensor_B.T)
result, result.shape

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])


(tensor([[ 27,  30,  33],
         [ 61,  68,  75],
         [ 95, 106, 117]]), torch.Size([3, 3]))

In [ ]:
torch.min(tensor_B @ tensor_A.T)

tensor(27)

In [ ]:
torch.sum(tensor_A)

tensor(21)

In [ ]:
torch.sum(tensor_A @ tensor_B.T)

tensor(612)

In [ ]:
tensor_A.min(), tensor_A.max()

(tensor(1), tensor(6))

In [ ]:
tensor_A.type(torch.float32).mean()

tensor(3.5000)

In [ ]:
tensor_A.type(torch.float32).mean()

tensor(3.5000)

In [ ]:
tensor_A.sum()

tensor(21)

In [ ]:
tensor_A.type(torch.float16).mean()

tensor(3.5000, dtype=torch.float16)

In [ ]:
# Finding the positional min and max
tensor_A[0][0] = 9
tensor_A, tensor_A.argmin()

(tensor([[9, 2],
         [3, 4],
         [5, 6]]), tensor(1))

In [ ]:
tensor_A.argmax()

tensor(0)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
** also `torch.stack(dim=N)`
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - adds a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x.reshape(9, 1)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z also changes x
z[0][1] = 99
x

tensor([ 1., 99.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked, x_stacked.shape

(tensor([[ 1.,  1.,  1.,  1.],
         [99., 99., 99., 99.],
         [ 3.,  3.,  3.,  3.],
         [ 4.,  4.,  4.,  4.],
         [ 5.,  5.,  5.,  5.],
         [ 6.,  6.,  6.,  6.],
         [ 7.,  7.,  7.,  7.],
         [ 8.,  8.,  8.,  8.],
         [ 9.,  9.,  9.,  9.]]), torch.Size([9, 4]))

In [ ]:
# Squeeze and unsqueeze - removes all single dimensions from a single tensor
to_squeeze = torch.zeros(2, 1, 2, 1, 2)
to_squeeze.shape, torch.squeeze(to_squeeze, 1).shape

(torch.Size([2, 1, 2, 1, 2]), torch.Size([2, 2, 1, 2]))

In [ ]:
x_reshaped, x_reshaped.shape

(tensor([[ 1., 99.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]), torch.Size([1, 9]))

In [ ]:
x_squeezed = x_reshaped.squeeze()
x_reshaped.shape, x_squeezed.shape # note squeezed is just index[0] of the tensor!

(torch.Size([1, 9]), torch.Size([9]))

In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
print(f'Previous target: {x_squeezed}')
print(f'Previous shape: {x_squeezed.shape}')

# add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f'\nNew tensor: {x_unsqueezed}')
print(f'New shape: {x_unsqueezed.shape}')

Previous target: tensor([ 1., 99.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])
Previous shape: torch.Size([9])

New tensor: tensor([[ 1., 99.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute - rearranges dimensions of target tensor in specified order

to_permute = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(f'to_permute size: {to_permute.size()}')
permuted = torch.permute(to_permute, (1, 0))
print(f'\nto_permute:\n{to_permute}\npermuted:\n{permuted}')

to_permute size: torch.Size([3, 3])

to_permute:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
permuted:
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])


# Permute

* used with images to move the channels around

In [ ]:
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color channels]

# Permute to move the color channels to the first dimension
x_permuted = x_original.permute(2, 0, 1) # shifts 0->1, 1->2, 2->0
print(f'Previous shape: {x_original.shape}\npermuted:\n{x_permuted.shape}')

Previous shape: torch.Size([224, 224, 3])
permuted:
torch.Size([3, 224, 224])


In [ ]:
x_permuted[0][0][0] = 9

In [ ]:
x_original[0][0] # should be the same as inserted via x_permuted

tensor([9.0000, 0.5050, 0.1052])

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][0][0]

tensor(1)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
# You can also use ':' to select 'all' of a target dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimensions
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
# index on x to return 9
nine = x[0, 2, 2]

#index on x to return 3, 6, 9
threesixnine = x[:, :, 2]

nine, threesixnine

(tensor(9), tensor([[3, 6, 9]]))

## PyTorch tensors & NumPy

NumPy is a populara scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)` 
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Note that the torch default is float32, but numpy is float64, so convert as below if desired

array.dtype, torch.from_numpy(array).type(torch.float32)


(dtype('float64'), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Change the value of array, what will this do to tensor?

array[0] = 99
array, tensor

(array([99.,  2.,  3.,  4.,  5.,  6.,  7.]),
 tensor([99.,  2.,  3.,  4.,  5.,  6.,  7.], dtype=torch.float64))

In [ ]:
tensor[1] = 77
array, tensor

(array([99., 77.,  3.,  4.,  5.,  6.,  7.]),
 tensor([99., 77.,  3.,  4.,  5.,  6.,  7.], dtype=torch.float64))

## Reproducibility (trying to take the random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to make them better representations of the data -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavor" the randomness.

In [ ]:
import torch

# create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.0429, 0.9589, 0.2727, 0.4389],
        [0.3340, 0.2596, 0.1361, 0.6734],
        [0.6562, 0.0107, 0.5521, 0.8794]])
tensor([[0.0593, 0.6473, 0.6779, 0.8174],
        [0.9823, 0.3215, 0.2981, 0.2018],
        [0.6985, 0.9478, 0.3407, 0.7439]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# let's make some random but reproducible tensors
import torch

# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED) # re-seed before every call
random_tensor_D = torch.rand(3, 4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Extra resources about reproducibility

* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTorch objects on GPUs (and making faster computations)

GPUS = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky-dory.

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU. Collab Pro gives you access to faster GPUs (options to upgrade).

2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU. Lots of options... (search for `the best gpus for deep learning in 2022`) [Tim Dettmer's 2022 hardware recommendations](https://timdettmers.com/2018/12/16/deep-learning-hardware-guide/#:~:text=For%20good%20cost%2Fperformance%2C%20I,but%20not%2016%2Dbit)) and [Tim Dettmer's general GPU recommendations for deep learning](https://timdettmers.com/2020/09/07/which-gpu-for-deep-learning/).

3. Use cloud computing such as GCP/AWS/Azure.

For 2, 3 PyTorch + GPU drivers (CUDA) takes a bit of setup, [read the pytorch docs](https://pytorch.org/get-started/locally/).

In [ ]:
!nvidia-smi

Tue Dec 13 14:02:44 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   72C    P0    32W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Check for GPU access with PyTorch

In [ ]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count the number of GPUs
torch.cuda.device_count()

1

## Best Practices

[PyTorch best practices doc](https://pytorch.org/docs/stable/notes/cuda.html#best-practices)

```
import argparse
import torch

parser = argparse.ArgumentParser(description='PyTorch Example')
parser.add_argument('--disable-cuda', action='store_true',
                    help='Disable CUDA')
args = parser.parse_args()
args.device = None
if not args.disable_cuda and torch.cuda.is_available():
    args.device = torch.device('cuda')
else:
    args.device = torch.device('cpu')

# Now that we have args.device, we can use it to create a Tensor on the desired device.

x = torch.empty((8, 42), device=args.device)
net = Network().to(device=args.device)


# This can be used in a number of cases to produce device agnostic code. Below is an example when using a dataloader:

cuda0 = torch.device('cuda:0')  # CUDA GPU 0
for i, x in enumerate(train_loader):
    x = x.to(cuda0)
```

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [ ]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3], device="cpu") # cpu is default

# Tensor not on GPU:
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
### 4. Moving tensors back to the CPU

tensor_on_cpu = tensor_on_gpu.to("cpu")
tensor_on_cpu, tensor_on_gpu

numpy_tensor = tensor_on_cpu.numpy()

try:
  tensor_on_gpu.numpy()
except Exception as e:
  print("that's right, can't convert to numpy with gpu")

numpy_tensor, tensor_on_cpu, tensor_on_gpu

that's right, can't convert to numpy with gpu


(array([1, 2, 3]), tensor([1, 2, 3]), tensor([1, 2, 3], device='cuda:0'))

## Exercises and Extra-curriculum

[learnpytorch.io exercises](https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises) and [notebook](https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb)